import type { NextConfig } from "next";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Legacy WP 301 map — generated by scripts/migrate-wp.ts, never hand-edited.
const legacyRedirects = JSON.parse(
  readFileSync(join(process.cwd(), "redirects", "legacy-redirects.json"), "utf8"),
) as Array<{ source: string; destination: string; permanent: boolean }>;

// The exact deployment host — a "*.convex.cloud" wildcard would NOT match
// multi-label hosts like <name>.eu-west-1.convex.cloud.
const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;

const nextConfig: NextConfig = {
  images: {
    remotePatterns: convexUrl
      ? [
          {
            protocol: "https" as const,
            hostname: new URL(convexUrl).hostname,
            pathname: "/api/storage/**",
          },
        ]
      : [],
  },
  async redirects() {
    return legacyRedirects;
  },
};

export default nextConfig;
