/**
 * Curated search aliases per category slug (Prilog A of the plan).
 * Folded into every company's searchText columns so common colloquial
 * Serbian/German terms hit the right companies despite Convex having no
 * stemming. Extend freely — recomputeSearchText picks changes up on the
 * next write (or a migration re-run).
 */
export const CATEGORY_ALIASES: Record<string, string[]> = {
  gradjevinarstvo: [
    "gradnja",
    "bau",
    "baufirma",
    "zidar",
    "fasada",
    "montazne kuce",
    "renoviranje",
    "sanierung",
  ],
  nekretnine: [
    "stan",
    "wohnung",
    "kuca",
    "haus",
    "immobilien",
    "izdavanje",
    "prodaja",
    "makler",
  ],
  servisi: [
    "vodoinstalater",
    "instalater",
    "installateur",
    "klempner",
    "elektricar",
    "elektriker",
    "klima",
    "grejanje",
    "heizung",
    "solar",
    "majstor",
    "ciscenje",
    "reinigung",
  ],
  auto: [
    "mehanicar",
    "mechaniker",
    "werkstatt",
    "autoservis",
    "limar",
    "vulkanizer",
    "auto skola",
    "fahrschule",
  ],
  prevoz: [
    "transport",
    "spedicija",
    "spedition",
    "selidbe",
    "umzug",
    "kombi prevoz",
    "prevoz putnika",
  ],
  proizvodnja: [
    "stolarija",
    "tischler",
    "namestaj",
    "moebel",
    "mobel",
    "ograde",
    "terase",
    "paneli",
    "pelet",
  ],
  trgovina: [
    "prodavnica",
    "geschaft",
    "shop",
    "veleprodaja",
    "handel",
    "grosshandel",
  ],
  zdravlje: [
    "zubar",
    "stomatolog",
    "zahnarzt",
    "ordinacija",
    "arzt",
    "lekar",
    "apoteka",
  ],
  nega: ["frizer", "friseur", "kozmeticar", "kosmetik", "salon", "masaza", "massage"],
  "strucne-usluge": [
    "advokat",
    "rechtsanwalt",
    "prevodilac",
    "ubersetzer",
    "knjigovodja",
    "buchhaltung",
    "steuerberater",
    "it",
    "racunovodstvo",
  ],
  turizam: ["apartman", "smestaj", "unterkunft", "banja", "letovanje", "reise"],
  ugostiteljstvo: [
    "restoran",
    "restaurant",
    "kafic",
    "cafe",
    "hotel",
    "prenociste",
    "gasthaus",
  ],
  kultura: ["udruzenje", "verein", "umetnost", "kunst", "muzika", "musik"],
};
